LOCATION = 'madrid'
LATITUDE = 40.416729
LONGITUDE = -3.703339
SLEEP_TIME = 3600 #in seconds

ZODIAC_LIST = ['Aquarius', 'Aries', 'Cancer', 'Capricornus', 'Gemini', 'Leo', 'Libra', 'Pisces', 'Sagittarius', 'Scorpius', 'Taurus', 'Virgo']

# pin assigment for every led
LED.MOON.AQUARIUS =
LED.MOON.ARIES =
LED.MOON.CANCER =
LED.MOON.CAPRICORNUS =
LED.MOON.GEMINI =
LED.MOON.LEO =
LED.MOON.LIBRA =
LED.MOON.PISCES =
LED.MOON.SAGITTARIUS =
LED.MOON.SCORPIUS =
LED.MOON.TAURUS =
LED.MOON.VIRGO =

PIN_MOON_1 =
PIN_MOON_2 =
PIN_MOON_3 =
PIN_MOON_4 =

PIN_MERCURY_1 =
PIN_MERCURY_2 =
PIN_MERCURY_3 =
PIN_MERCURY_4 =

PIN_VENUS_1 =
PIN_VENUS_2 =
PIN_VENUS_3 =
PIN_VENUS_4 =

PIN_MARS_1 =
PIN_MARS_2 =
PIN_MARS_3 =
PIN_MARS_4 =

PIN_JUPITER_1 =
PIN_JUPITER_2 =
PIN_JUPITER_3 =
PIN_JUPITER_4 =

PIN_SAT_1 =
PIN_SAT_2 =
PIN_SAT_3 =
PIN_SAT_4 =

PIN_URANUS_1 =
PIN_URANUS_2 =
PIN_URANUS_3 =
PIN_URANUS_4 =

PIN_NEP_1 =
PIN_NEP_2 =
PIN_NEP_3 =
PIN_NEP_4 =

PIN_PLUTO_1 =
PIN_PLUTO_2 =
PIN_PLUTO_3 =
PIN_PLUTO_4 =